### ISSUE TITLE
Template panel does not render <script> tag correctly

### ISSUE THREAD

**Issue by thesayfulla** [django-commons/django-debug-toolbar#2041]
## Issue:
There is an issue with rendering `<script></script>` tags in the template panel. The template source incorrectly removes spaces(tabs) within the script tags, which causes the content to render incorrectly.

<img width="833" alt="395896872-7a1a32bc-4a85-45c3-8497-b9fe04c561d7" src="https://github.com/user-attachments/assets/a86a9f96-f913-4a08-a8ad-27eb92fcb90d" />

## Expected Behavior:
The `<script></script>` tags should render correctly with all spaces(tabs) intact, allowing for proper functionality.

**Comment by matthiask** [comment]
Using inline scripts in panels isn't supported at this time. You should use the `scripts` property of panels for this:
https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#debug_toolbar.panels.Panel.scripts

**Comment by matthiask** [comment]
We're using pygments for the highlighting (if it's available!) 

It seems that we're not applying the appropriate style to whitespace elements (`.w`) in our homegrown CSS (why do we even have our own CSS for highlighting when we could just be using pygment styles?)

**Comment by thesayfulla** [comment]
> We're using pygments for the highlighting (if it's available!)
> 
> It seems that we're not applying the appropriate style to whitespace elements (`.w`) in our homegrown CSS (why do we even have our own CSS for highlighting when we could just be using pygment styles?)

I've updated the code as follows:
```python
source = mark_safe(f"<code>{source}</code>")
```

file: [debug_toolbar/panels/templates/views.py#L60](https://github.com/django-commons/django-debug-toolbar/blob/main/debug_toolbar/panels/templates/views.py#L60)

### Result:
<img width="827" alt="Screenshot 2024-12-16 at 17 37 46" src="https://github.com/user-attachments/assets/571de590-a602-48af-854c-b0fd1ca61ae2" />
What do you think about implementing it this way?"
